services:
  postgres:
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: wallet
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    networks:
      - wallet_net

volumes:
  postgres-data:

networks:
  wallet_net: